# Feature Spec: Planned Check Behavioral Requirements

**Version:** 1.0
**Status:** Draft
**Section:** 4.13

## Requirements

| ID | Source | Title | Priority | Verification | Acceptance |
|-----|--------|-------|----------|--------------|------------|
| REQ-001 | FR-800 | Module discovery strategy | Must | Test | Module discovery detects Rust (`Cargo.toml`), JavaScript/TypeScript (`package.json`), Python (`setup.py`, `pyproject.toml`), and Java (`pom.xml`, `build.gradle`) project manifests. Projects without recognized manifests produce Skip for all module-level checks. |
| REQ-002 | FR-801 | W3H detection scope | Must | Test | W3H validation uses flexible regex `(?i)^##\s*(what |
| REQ-003 | FR-802 | Module deployment check skip behavior | Must | Test | Module deployment checks produce Skip (not Fail) for modules that have no `docs/6-deployment/` directory. Only modules with an existing `docs/6-deployment/` directory are validated for required files (`README.md`, `prerequisites.md`, `installation.md`). |
| REQ-004 | FR-803 | Feature-prefixed artifact check opt-in | Must | Test | Feature naming checks produce Skip if no files or directories matching `FR_\d{3}` exist anywhere in the project. When FR-prefixed artifacts do exist, folders must match `FR_\d{3}/` and files must match `FR_\d{3}_.+`. Hyphens (`FR-###`) in file paths produce a warning. |
| REQ-005 | FR-804 | Planning phase artifact verification | Should | Test | The tool shall verify that standard planning phase artifacts exist under `docs/2-planning/`: risk register (`risk_register.md`), estimation records (`estimation.md`), schedule (`schedule.md`), resource plan (`resource_plan.md`), communication plan (`communication_plan.md`), and quality plan (`quality_plan.md`). Each missing artifact produces an `info`-level finding. Schedule, resource plan, and communication plan are scoped to `open_source` projects only and produce `Skip` for internal projects. |
| REQ-006 | FR-805 | SRS 29148 attribute validation | Should | Test | Check 89 validates that every FR-xxx and NFR-xxx block in `docs/1-requirements/srs.md` contains the five mandatory ISO/IEC/IEEE 29148:2018 attributes: Priority, State, Verification, Traces to (or Traceability), and Acceptance. Missing attributes produce per-requirement violations. Projects without an SRS file or without FR/NFR blocks produce Skip. STK-xxx blocks are excluded (they use a consolidated table format). |
| REQ-007 | FR-806 | Architecture 42010 attribute validation | Should | Test | Check 90 validates that architecture documents at both project level (`docs/3-design/architecture.md`) and module level (`<module>/docs/3-design/architecture.md`) contain key ISO/IEC/IEEE 42010:2022 sections: stakeholder identification, architectural concerns/rationale, and viewpoints/views. Missing sections produce per-file violations. Projects and modules without an architecture file or with an empty file are skipped. If no architecture files exist anywhere, the check produces Skip. W3H sections (Who/Why/What/How) satisfy the 42010 requirements. |
| REQ-008 | FR-807 | Testing 29119-3 attribute validation | Should | Test | Check 91 validates that testing strategy documents at both project level (`docs/5-testing/testing_strategy.md`) and module level (`<module>/docs/5-testing/testing_strategy.md`) contain key ISO/IEC/IEEE 29119-3:2021 sections: test strategy/scope, test cases/categories, and coverage targets/criteria. Missing sections produce per-file violations. Projects and modules without a testing strategy file or with an empty file are skipped. If no testing strategy files exist anywhere, the check produces Skip. |
| REQ-009 | FR-808 | Production readiness document existence | Should | Test | Check 92 validates that `docs/6-deployment/production_readiness.md` exists. Projects without this file produce Skip. |
| REQ-010 | FR-809 | Production readiness ISO/IEC 25010:2023 quality sections | Should | Test | Check 93 validates that `docs/6-deployment/production_readiness.md` contains sections for Security, Test Coverage, Observability, Backwards Compatibility, Runtime Safety, and Verdict. Missing sections produce per-section violations. Projects without the file produce Skip. |
| REQ-011 | FR-810 | Developer guide ISO/IEC/IEEE 26514:2022 sections | Should | Test | Check 94 validates that `docs/4-development/developer_guide.md` contains sections for Build & Test, Project Structure, and Adding New Features. Missing sections produce per-section violations. Projects without the file produce Skip. |
| REQ-012 | FR-811 | Backlog content sections | Should | Test | Check 95 validates that `docs/2-planning/backlog.md` contains sections for Backlog Items (or High Priority), Completed, and Blockers. Missing sections produce per-section violations. Projects without the file produce Skip. |
| REQ-013 | FR-812 | Production readiness ISO/IEC/IEEE 12207:2017 lifecycle sections | Should | Test | Check 96 validates that `docs/6-deployment/production_readiness.md` contains sections for CI/CD Pipeline, Dependency Health, Dependency Auditing, Package Metadata, and Release Automation. Missing sections produce per-section violations. Projects without the file produce Skip. |
| REQ-014 | FR-813 | Production readiness supplementary ISO/IEC 25010:2023 quality sections | Should | Test | Check 97 validates that `docs/6-deployment/production_readiness.md` contains sections for Static Analysis, API Documentation, README & Onboarding, and Documentation Lint. Missing sections produce per-section violations. Projects without the file produce Skip. |
| REQ-015 | FR-814 | Production readiness ISO/IEC 25040:2024 evaluation sections | Should | Test | Check 98 validates that `docs/6-deployment/production_readiness.md` contains Scoring and Sign-Off sections. The Scoring section defines evaluation criteria (PASS/WARN/FAIL). The Sign-Off section captures role, name, date, and verdict. Missing sections produce per-section violations. Projects without the file produce Skip. |
| REQ-016 | FR-815 | Phase artifact file existence checks | Must | Test | The tool shall verify that ISO-mandated documentation artifacts exist for each SDLC phase. Each missing artifact produces a finding at the configured severity. All checks are declarative `file_exists` rules — no Rust code required. |
| REQ-017 | FR-816 | Cross-phase and gap-closure artifact checks | Must | Test | The tool shall verify existence of 6 additional ISO-mandated artifacts: ConOps (29148 Annex B), StRS (29148 Cl. 6.2), traceability matrix (29148 Cl. 5.2.6), progress reports (12207 Cl. 6.3.2), decision log (12207 Cl. 6.3.3), audit report (15289 Cl. 9.2), with IEEE 1028 content validation (check 124). |
| REQ-018 | FR-817 | Audit report IEEE 1028 content validation | Should | Test | Check 124 validates that `docs/2-planning/audit_report.md` contains Scope, Findings, and Recommendations sections per IEEE 1028 clause 4. Missing sections produce per-section violations. Projects without the file produce Skip. |
| REQ-019 | FR-818 | Test plan ISO/IEC/IEEE 29119-3 content validation | Should | Test | Check 125 validates that `docs/5-testing/test_plan.md` contains Objectives/scope, Schedule/milestones, and Environment/resources sections per 29119-3 clause 7. Missing sections produce per-section violations. Projects without the file produce Skip. |
| REQ-020 | FR-819 | Test design ISO/IEC/IEEE 29119-3 content validation | Should | Test | Check 126 validates that `docs/5-testing/test_design.md` contains Test conditions, Test coverage, and Traceability sections per 29119-3 clause 8. Missing sections produce per-section violations. Projects without the file produce Skip. |
| REQ-021 | FR-820 | Test cases ISO/IEC/IEEE 29119-3 content validation | Should | Test | Check 127 validates that `docs/5-testing/test_cases.md` contains Test case ID/title, Pre-conditions/steps, and Expected results sections per 29119-3 clause 9. Missing sections produce per-section violations. Projects without the file produce Skip. |
| REQ-022 | FR-821 | Verification report ISO/IEC/IEEE 29119-3 content validation | Should | Test | Check 128 validates that `docs/5-testing/verification_report.md` contains Summary/results, Pass/fail status, and Defects/issues sections per 29119-3 clause 10. Missing sections produce per-section violations. Projects without the file produce Skip. |

## Acceptance Criteria

- **REQ-001** (FR-800): Module discovery detects Rust (`Cargo.toml`), JavaScript/TypeScript (`package.json`), Python (`setup.py`, `pyproject.toml`), and Java (`pom.xml`, `build.gradle`) project manifests. Projects without recognized manifests produce Skip for all module-level checks.
- **REQ-002** (FR-801): W3H validation uses flexible regex `(?i)^##\s*(what
- **REQ-003** (FR-802): Module deployment checks produce Skip (not Fail) for modules that have no `docs/6-deployment/` directory. Only modules with an existing `docs/6-deployment/` directory are validated for required files (`README.md`, `prerequisites.md`, `installation.md`).
- **REQ-004** (FR-803): Feature naming checks produce Skip if no files or directories matching `FR_\d{3}` exist anywhere in the project. When FR-prefixed artifacts do exist, folders must match `FR_\d{3}/` and files must match `FR_\d{3}_.+`. Hyphens (`FR-###`) in file paths produce a warning.
- **REQ-005** (FR-804): The tool shall verify that standard planning phase artifacts exist under `docs/2-planning/`: risk register (`risk_register.md`), estimation records (`estimation.md`), schedule (`schedule.md`), resource plan (`resource_plan.md`), communication plan (`communication_plan.md`), and quality plan (`quality_plan.md`). Each missing artifact produces an `info`-level finding. Schedule, resource plan, and communication plan are scoped to `open_source` projects only and produce `Skip` for internal projects.
- **REQ-006** (FR-805): Check 89 validates that every FR-xxx and NFR-xxx block in `docs/1-requirements/srs.md` contains the five mandatory ISO/IEC/IEEE 29148:2018 attributes: Priority, State, Verification, Traces to (or Traceability), and Acceptance. Missing attributes produce per-requirement violations. Projects without an SRS file or without FR/NFR blocks produce Skip. STK-xxx blocks are excluded (they use a consolidated table format).
- **REQ-007** (FR-806): Check 90 validates that architecture documents at both project level (`docs/3-design/architecture.md`) and module level (`<module>/docs/3-design/architecture.md`) contain key ISO/IEC/IEEE 42010:2022 sections: stakeholder identification, architectural concerns/rationale, and viewpoints/views. Missing sections produce per-file violations. Projects and modules without an architecture file or with an empty file are skipped. If no architecture files exist anywhere, the check produces Skip. W3H sections (Who/Why/What/How) satisfy the 42010 requirements.
- **REQ-008** (FR-807): Check 91 validates that testing strategy documents at both project level (`docs/5-testing/testing_strategy.md`) and module level (`<module>/docs/5-testing/testing_strategy.md`) contain key ISO/IEC/IEEE 29119-3:2021 sections: test strategy/scope, test cases/categories, and coverage targets/criteria. Missing sections produce per-file violations. Projects and modules without a testing strategy file or with an empty file are skipped. If no testing strategy files exist anywhere, the check produces Skip.
- **REQ-009** (FR-808): Check 92 validates that `docs/6-deployment/production_readiness.md` exists. Projects without this file produce Skip.
- **REQ-010** (FR-809): Check 93 validates that `docs/6-deployment/production_readiness.md` contains sections for Security, Test Coverage, Observability, Backwards Compatibility, Runtime Safety, and Verdict. Missing sections produce per-section violations. Projects without the file produce Skip.
- **REQ-011** (FR-810): Check 94 validates that `docs/4-development/developer_guide.md` contains sections for Build & Test, Project Structure, and Adding New Features. Missing sections produce per-section violations. Projects without the file produce Skip.
- **REQ-012** (FR-811): Check 95 validates that `docs/2-planning/backlog.md` contains sections for Backlog Items (or High Priority), Completed, and Blockers. Missing sections produce per-section violations. Projects without the file produce Skip.
- **REQ-013** (FR-812): Check 96 validates that `docs/6-deployment/production_readiness.md` contains sections for CI/CD Pipeline, Dependency Health, Dependency Auditing, Package Metadata, and Release Automation. Missing sections produce per-section violations. Projects without the file produce Skip.
- **REQ-014** (FR-813): Check 97 validates that `docs/6-deployment/production_readiness.md` contains sections for Static Analysis, API Documentation, README & Onboarding, and Documentation Lint. Missing sections produce per-section violations. Projects without the file produce Skip.
- **REQ-015** (FR-814): Check 98 validates that `docs/6-deployment/production_readiness.md` contains Scoring and Sign-Off sections. The Scoring section defines evaluation criteria (PASS/WARN/FAIL). The Sign-Off section captures role, name, date, and verdict. Missing sections produce per-section violations. Projects without the file produce Skip.
- **REQ-016** (FR-815): The tool shall verify that ISO-mandated documentation artifacts exist for each SDLC phase. Each missing artifact produces a finding at the configured severity. All checks are declarative `file_exists` rules — no Rust code required.
- **REQ-017** (FR-816): The tool shall verify existence of 6 additional ISO-mandated artifacts: ConOps (29148 Annex B), StRS (29148 Cl. 6.2), traceability matrix (29148 Cl. 5.2.6), progress reports (12207 Cl. 6.3.2), decision log (12207 Cl. 6.3.3), audit report (15289 Cl. 9.2), with IEEE 1028 content validation (check 124).
- **REQ-018** (FR-817): Check 124 validates that `docs/2-planning/audit_report.md` contains Scope, Findings, and Recommendations sections per IEEE 1028 clause 4. Missing sections produce per-section violations. Projects without the file produce Skip.
- **REQ-019** (FR-818): Check 125 validates that `docs/5-testing/test_plan.md` contains Objectives/scope, Schedule/milestones, and Environment/resources sections per 29119-3 clause 7. Missing sections produce per-section violations. Projects without the file produce Skip.
- **REQ-020** (FR-819): Check 126 validates that `docs/5-testing/test_design.md` contains Test conditions, Test coverage, and Traceability sections per 29119-3 clause 8. Missing sections produce per-section violations. Projects without the file produce Skip.
- **REQ-021** (FR-820): Check 127 validates that `docs/5-testing/test_cases.md` contains Test case ID/title, Pre-conditions/steps, and Expected results sections per 29119-3 clause 9. Missing sections produce per-section violations. Projects without the file produce Skip.
- **REQ-022** (FR-821): Check 128 validates that `docs/5-testing/verification_report.md` contains Summary/results, Pass/fail status, and Defects/issues sections per 29119-3 clause 10. Missing sections produce per-section violations. Projects without the file produce Skip.

